lane :bonjour do

  # if UI.confirm("Sure dude ?")
  #  UI.success "Cooool !"
  # else
  #  UI.error "Hmm ?"
  # end
  scan
end

lane :deploy do
  if git_branch() == "master"
    version = get_version_number()
    set_github_release(
      repository_name: "mrancois/fastlane-demo",
      name: version, #nom de la version sur Github
      tag_name: "v#{version}",
      description: changelog_from_git_commits(),
      commitish: "master"
    )
  end
end
